access:
  getPlanets: "https://swapi.dev/api/planets/"

spring:
  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27017}
      database: starwars

server:
  servlet:
    context-path: /api
  error:
    include-message: always
  port: 8080